import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { LoadingProvider } from '@/context/loadingContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Aerius Labs',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='m-0 cursor-none p-0'>
      <body className={`${inter.className} m-0 p-0`}>
        <LoadingProvider>{children}</LoadingProvider>
      </body>
    </html>
  );
}
